name: MainPlugin
version: 1.16.2
api-version: 1.16
main: de.redoxcraft.mainplugin.main.Main
author: RedoxCraft
website: https://www.youtube.com/redoxcraft

commands:
   gm:
   
   sv:
   
   spec:
   
   adven: